version: "3.7"
services:
 backend: 
   build: ./backend
   environment:
    - APP_PORT=3001
    - JWT_SECRET=jwt_secret
    - DB_USER=postgres
    - DB_PASS=123456
    - DB_HOST=db
    - DB_PORT=5432
   ports:
    - "3001:3001"
   networks:
    - twotier
   depends_on:
     - db
 db:
  image: postgres:15.1
  environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
  networks:
    - twotier
  ports:
   - "5432:5432"
networks:
  twotier:
     
